### ISSUE TITLE
RemoteRepository attr "password" is not JSON Serializable

### ISSUE THREAD

**Issue by ajrpeggio** [anancarv/python-artifactory#74]
**Describe the bug**
I've been using this library to create repositories for my Artifactory Instance. I started adding a RemoteRepository for docker and came upon this error that states: "Object of type SecretStr is not JSON serializable"

**To Reproduce**
```python
from pyartifactory import Artifactory
from pyartifactory.models import RemoteRepository

url = <url to artifactory instance>
auth = (<username>, <password>)
remote_docker_repo_cfg = {
    "key": "docker-remote",
    "url": "https://registry-1.docker.io/",
    "packageType": "docker",
    "username": <dockerhub username>,
    "password": <dockerhub_password>,
}
rt = Artifactory(url=url, auth=auth)
remote_repo = RemoteRepository(**remote_docker_repo_cfg)
rt.repositories.create_repo(remote_repo)
```

This sequence of events will cause the following error to be thrown:
```
Repository docker-remote does not exist
Traceback (most recent call last):
  File "/Users/aj.rasmussen/Library/Python/3.8/lib/python/site-packages/pyartifactory/objects.py", line 434, in get_repo
    response = self._get(f"api/{self._uri}/{repo_name}")
  File "/Users/aj.rasmussen/Library/Python/3.8/lib/python/site-packages/pyartifactory/objects.py", line 97, in _get
    return self._generic_http_method_request("get", route, **kwargs)
  File "/Users/aj.rasmussen/Library/Python/3.8/lib/python/site-packages/pyartifactory/objects.py", line 142, in _generic_http_method_request
    response.raise_for_status()
  File "/Users/aj.rasmussen/Library/Python/3.8/lib/python/site-packages/requests/models.py", line 943, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: http://artifactory.prod.vyopta.com:8082/artifactory/api/repositories/docker-remote

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/aj.rasmussen/Library/Python/3.8/lib/python/site-packages/pyartifactory/objects.py", line 460, in create_repo
    self.get_repo(repo_name)
  File "/Users/aj.rasmussen/Library/Python/3.8/lib/python/site-packages/pyartifactory/objects.py", line 447, in get_repo
    raise RepositoryNotFoundException(
pyartifactory.exception.RepositoryNotFoundException:  Repository docker-remote does not exist

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/aj.rasmussen/Library/Python/3.8/lib/python/site-packages/pyartifactory/objects.py", line 466, in create_repo
    self._put(f"api/{self._uri}/{repo_name}", json=repo.dict())
  File "/Users/aj.rasmussen/Library/Python/3.8/lib/python/site-packages/pyartifactory/objects.py", line 113, in _put
    return self._generic_http_method_request("put", route, **kwargs)
  File "/Users/aj.rasmussen/Library/Python/3.8/lib/python/site-packages/pyartifactory/objects.py", line 134, in _generic_http_method_request
    response: Response = http_method(
  File "/Users/aj.rasmussen/Library/Python/3.8/lib/python/site-packages/requests/sessions.py", line 602, in put
    return self.request('PUT', url, data=data, **kwargs)
  File "/Users/aj.rasmussen/Library/Python/3.8/lib/python/site-packages/requests/sessions.py", line 528, in request
    prep = self.prepare_request(req)
  File "/Users/aj.rasmussen/Library/Python/3.8/lib/python/site-packages/requests/sessions.py", line 456, in prepare_request
    p.prepare(
  File "/Users/aj.rasmussen/Library/Python/3.8/lib/python/site-packages/requests/models.py", line 319, in prepare
    self.prepare_body(data, files, json)
  File "/Users/aj.rasmussen/Library/Python/3.8/lib/python/site-packages/requests/models.py", line 469, in prepare_body
    body = complexjson.dumps(json)
  File "/usr/local/Cellar/python@3.8/3.8.6_2/Frameworks/Python.framework/Versions/3.8/lib/python3.8/json/__init__.py", line 231, in dumps
    return _default_encoder.encode(obj)
  File "/usr/local/Cellar/python@3.8/3.8.6_2/Frameworks/Python.framework/Versions/3.8/lib/python3.8/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/local/Cellar/python@3.8/3.8.6_2/Frameworks/Python.framework/Versions/3.8/lib/python3.8/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/usr/local/Cellar/python@3.8/3.8.6_2/Frameworks/Python.framework/Versions/3.8/lib/python3.8/json/encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type SecretStr is not JSON serializable
```

**Expected behavior**
I expected the docker-remote repository to be created with the credentials in place but it seems that the "SecretStr" object is being passed to the JSON serializer in the code.

**Screenshots**

**Environment:**
 - OS: macOS
 - pyartifactory version [e.g. 1.8.0], get it with:
```
python3.8 -c "import pyartifactory; print(pyartifactory.__version__)"
```
 - Python version, get it with:
```
python3.8 --version
```

**Comment by ajrpeggio** [comment]
I updated pyartifactory/models/repository.py, line 227 for ```Class RemoteRepository``` from ```Optional[SecretStr]``` to ```Optional[str]``` locally and it created the remote repo just fine.

**Comment by anancarv** [comment]
Hi @ajrpeggio ,
Thanks for pointing this issue out. You can make a PR with this modification. I'll be glad to merge it :)
